Task
RayzOnePy/Laravel pull request #1
Opened 2023-11-13 14:56 UTC by RayzOnePy

Я уверен что у меня миллион косяков. мне скорее всего валидацию нужно будет переносить в другое место

2023-11-13 14:57 UTC, RayzOnePy commented
зато readme вроде неплохо получился

2023-11-14 05:10 UTC, jurapro requested changes
Не все так плохо, но постарайся учесть замечания

2023-11-14 05:10 UTC, jurapro commented on example-app/app/Http/Controllers/AuthController.php
> +        $validator = Validator::make($request->all(), $rules);
Валидации нужно вынести отдельно с использованием https://laravel.com/docs/10.x/validation#form-request-validation

2023-11-14 05:10 UTC, jurapro commented on example-app/app/Http/Controllers/AuthController.php
> +        $user = User::create([
можно передать $request->all()

2023-11-14 05:10 UTC, jurapro commented on example-app/app/Http/Controllers/AuthController.php
> +        } else {
else не нужен, у тебя же return

2023-11-14 05:10 UTC, jurapro commented on example-app/app/Http/Controllers/AuthController.php
> +        $validator = Validator::make($request->all(), $rules);
Дальше подобное комментировать не буду

2023-11-14 05:10 UTC, jurapro commented on example-app/app/Http/Controllers/AuthController.php
> +            return response()->json(['success' => true, 'code' => 200, 'message' => 'Success', 'token' => $token], 200);
Нужно использовать https://laravel.com/docs/10.x/eloquent-resources сделать шаблонный вывод и его юзать

2023-11-14 05:10 UTC, jurapro commented on example-app/app/Http/Controllers/FileController.php
> +            return response()->json(['message' => 'Not found', 'code' => 404], 404);
лучше сделать с помощью исключений https://laravel.com/docs/10.x/errors

2023-11-14 05:10 UTC, jurapro commented on example-app/app/Http/Controllers/FileController.php
> +            return response()->json(['message' => 'Not found', 'code' => 404], 404);
далее про это отмечать не буду

2023-11-14 05:10 UTC, jurapro commented on example-app/app/Models/File.php
> +    public static function findByName(int $userId, string $name): Model
Такое можно, но кастомные запросы над моделями выносятся обычно в билдеры https://martinjoo.dev/build-your-own-laravel-query-builders

2023-11-14 05:10 UTC, jurapro commented on example-app/app/Models/User.php
> +    public static function getByEmailAndPassword(string $email, string $password): ?Model
А что пароль в чистом виде хранится у пользователя?))

2023-11-14 06:28 UTC, RetmixX requested changes
Исправляйся

2023-11-14 06:28 UTC, RetmixX commented on example-app/app/Http/Controllers/FileController.php
> +        if ($file == null || Storage::fileExists($file->getPathWithName()) == null) {
is_null()

2023-11-14 06:28 UTC, RetmixX commented on example-app/app/Http/Controllers/FileController.php
> +        $fileNewPath = $filePath . '/' . $request['new_name'] . '.' . $file->getExtension();
"{}"

2023-11-14 06:28 UTC, RetmixX commented on example-app/app/Http/Controllers/FileController.php
> +        if ($file == null || Storage::fileExists($file->getPathWithName()) == null) {
is_null()

2023-11-14 06:28 UTC, RetmixX commented on example-app/database/seeders/UserSeeder.php
> +        DB::table('users')->insert([
https://laravel.com/docs/10.x/eloquent-factories
Через фабрики

2023-11-14 06:28 UTC, RetmixX commented on example-app/routes/api.php
> +Route::middleware('auth:sanctum')->group(function () {
crud операции над files перенеси в ресурсы
https://laravel.com/docs/10.x/controllers#resource-controllers

2023-11-15 03:35 UTC, jurapro approved these changes
Продолжай в том же духе)

2023-11-15 22:10 UTC, RetmixX commented on example-app/app/Exceptions/Handler.php
> +    private function handleApiException($request, Exception|Throwable $exception)
Попробуй такой вариант
![image](https://github.com/RayzOnePy/Laravel/assets/98283896/c667ffb7-8287-4a56-8c8b-3b001a328fdf)

2023-11-16 07:15 UTC, jurapro approved these changes

2023-11-16 12:54 UTC, jurapro approved these changes

2023-11-17 09:53 UTC, merged